### ISSUE TITLE
Media description

### ISSUE THREAD

**Issue by mkljczk** [Big-Fig/Fediverse.app#64]
- [x] Search for issues. Perhaps similar issue already opened

I can't find a way to add a media description when posting images on Fedi. I don't recall seeing a related string when translating, so I guess it might not be implemented yet.
That would probably be the only reason I still use browser for Pleroma now that #56 is correct

**Comment by xal** [comment]
@mkljczk yep, media description not implemented yet. Thanks for the feedback, I increased priority for this task
